#!/bin/bash

if [ $# -eq 0 ]; then
    echo "ファイルを指定してください"
    exit 2
fi

for i in $@
do
    if [ ! -f $i ]; then
        echo "$i というファイルは存在しません"
        exit 2
    fi
done

dogmatize=$(($RANDOM % $#))
shift $dogmatize

cat $1
